### ISSUE TITLE
Error when setting pyPath in writeScoreCode

### ISSUE THREAD

**Issue by sahbic** [sassoftware/open-model-manager-resources#12]
When setting a folder with pyPath parameter in writeScoreCode, there is a TypeError:

ScoreCode.writeScoreCode(inputDF, targetDF, modelPrefix,'{}.predict_proba({})', modelPrefix + '.pickle',pyPath=zipFolder)

```
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
It seems that the function fails to generate the path.

![image](https://user-images.githubusercontent.com/4807254/84677385-eeebab00-af2e-11ea-827c-1ada0c719ac0.png)

**Comment by smlindauer** [comment]
Thanks for the bug report @sahbic. It looks as though if the path format provided to the writeScoreCode() function is not from the pathlib library, a TypeError will be generated.

A simple fix can be applied by changing line 72 to:
`pyPath = Path(pyPath) / (modelPrefix + 'Score.py')`
as the pathlib library converts provided paths into pathlib.

**Comment by kaponte75** [comment]
The pzmm has been removed from this repository, so closing this issue.
FYI - the pzmm code is located in the python-sasctl repository https://github.com/sassoftware/python-sasctl/blob/master/src/sasctl/pzmm/ repository.
