### ISSUE TITLE
Can not publish the sample model

### ISSUE THREAD

**Issue by dqin2019** [sassoftware/open-model-manager-resources#14]
I am using the SAS Model Manager online. I was trying to import the python model (Decision Tree) but I have got this error: 
`You cannot publish the model "hmeqClassTree" to the SAS Micro Analytic Service because the model score code is not supported. The score code type must be "DATA step", "DS2 package", or "DS2 multi-type".`

**Comment by smlindauer** [comment]
Hey @dqin2019,

What version of SAS Model Manager are you using? When you run a publish or score action with Python score code, the most recent versions of SAS Model Manager and SAS Open Model Manager will wrap the score code in DS2, which can then be published to the maslocal (SAS Micro Analytic Service) destination.

**Comment by dqin2019** [comment]
@smlindauer Hi Scott, thanks for the reply. I just found the link:
https://documentation.sas.com/?docsetId=mdlmgrug&docsetTarget=n026ttfq4xcn5an19dpfo4jcyuqz.htm&docsetVersion=15.3&locale=en#p01jsm3kr3z8j0n11xjx7lol75an
I thought it can directly read the .py file and generate the score code. After I manually generate the .sas file, then I can publish the model.
My version is Model Manager v15.3
Thanks for your answer!

**Comment by kaponte75** [comment]
@dqin2019 
The SAS Model Manager 15.3: Quick Start Tutorial goes through the steps for testing and publishing a Python model. Including the requirements for the Python score code file. Let us know if you have any questions and if you were able to successfully publish your model to SAS Micro Analytic Service.
https://go.documentation.sas.com/?cdcId=mdlmgrcdc&cdcVersion=15.3&docsetId=mdlmgrqs&docsetTarget=p1qjiqn6mcrdk6n1c4egttfhjrhd.htm&locale=en
