### ISSUE TITLE
Variable Name Syntax Error 

### ISSUE THREAD

**Issue by SophiaRowland** [sassoftware/open-model-manager-resources#15]
The one-hot-encoding used in writeScoreCode.py of the pzmm package needs additional validation before generating variable names. In example, a column titled emp_length which included a value of '< 1 year' tried to create a column named 'emp_length_< 1 year'  in the score.py file. 

The strip() function at line 176 only removes the leading and trailing spaces. It leaves spaces between characters and special characters, leading to later syntax errors.  I would suggest adding uniq =uniq.replace(" ", "_") to replace the spaces with underscores and perhaps using re.sub() from the re package to remove special characters.

**Comment by smlindauer** [comment]
Thanks @SophiaRowland for the bug report and suggested fixes.

FYI, work on pzmm has been stopped inside this repository as pzmm has moved to [python-sasctl as a module](https://github.com/sassoftware/python-sasctl/tree/master/src/sasctl/pzmm). As such, I'm going to move this issue to the sasctl repository and close it for open-model-manager-resources.

**Comment by smlindauer** [comment]
Here is the moved issue: https://github.com/sassoftware/python-sasctl/issues/69.
