### ISSUE TITLE
mmAuthorization.py is required for Juypter notebook

### ISSUE THREAD

**Issue by Andy-Tr** [sassoftware/open-model-manager-resources#18]
When trying to use CreateAWSDestination.ipynb as a python file, the mmAuthorization import fails.  
Traceback (most recent call last):
  File "CreateAWSDestination.py", line 3, in <module>
    import mmAuthorization
ModuleNotFoundError: No module named 'mmAuthorization'

The prerequisites don't mention that you need this file to run the playbook or use the python code.

**Comment by kaponte75** [comment]
This related destination Jupyter notebook has been replaced with a CLI example, which does not reference the mmAuthorization.py file.
