### ISSUE TITLE
NameError in CreateAWSDestination.ipynb

### ISSUE THREAD

**Issue by Andy-Tr** [sassoftware/open-model-manager-resources#19]
There are multiple NameError tracebacks when running CreateAWSDestination as a python script:

Traceback (most recent call last):
  File "CreateAWSDestination.py", line 29, in <module>
    my_credential_url = my_domain_url + "/users/" + user_credential_name
NameError: name 'my_domain_url' is not defined

Traceback (most recent call last):
  File "CreateAWSDestination.py", line 39, in <module>
    "domainId":domain_name,
NameError: name 'domain_name' is not defined

Traceback (most recent call last):
  File "CreateAWSDestination.py", line 58, in <module>
    credentialURL = domains_url + domain_name + '/credentials'
NameError: name 'domains_url' is not defined

**Comment by kaponte75** [comment]
The related destination Jupyter notebook has been deprecated and replaced with a CLI example. The models plug-in to the SAS Viya CLI creates the base64 credentials domain when creating the AWS publishing destination.
