### ISSUE TITLE
Domain not created running CreateAWSDestination

### ISSUE THREAD

**Issue by Andy-Tr** [sassoftware/open-model-manager-resources#20]
The CreateAWSDestination python code does not create the domain so the request to create the credentials to
/credentials/domains/users/<user_name> fails with a 404.  
Note, that path isn't correct either.
.
I had to add in a creation of a domain of type base64:

my_domain_url = my_domain_url + "/" + domain_name

domain_put_header = {
    "Content-Type":"application/vnd.sas.credential.domain+json",
    "Accept":"application/vnd.sas.credential.domain+json",
    mmAuthorization.AUTHORIZATION_HEADER: mmAuthorization.AUTHORIZATION_TOKEN + admin_auth_token
}

domain_attrs = {
    "id":domain_name,
    "type":"base64",  # Switch to base64 from password
    "description":"AWS credentials"
}

domain = requests.put(my_domain_url,
                       data=json.dumps(domain_attrs), headers=domain_put_header,verify=my_verify)

That then switched my credential url to
my_credential_url = my_domain_url + "/users/" + user_credential_name
which became  /credentials/domains/<my_domain>/users/<user_name>

That allowed the credentials to be added successfully.

**Comment by kaponte75** [comment]
The related destination Jupyter notebook has been deprecated and replaced with a CLI example. The models plug-in to the SAS Viya CLI creates the base64 domain when creating the AWS publishing destination.
