### ISSUE TITLE
Git Publishing Destination - Create a New Destination step fails

### ISSUE THREAD

**Issue by bteleuca** [sassoftware/open-model-manager-resources#28]
_Create a New Destination_ step fails with message:

![image](https://user-images.githubusercontent.com/47585929/148147684-7cb1bc7f-0fb9-490b-8367-d37f5a2e397d.png)

My best guess is, that in the _Define a Git Destination_ step

in:

```
targetDestination={
    "name":destName,
    "destinationType":"git",
    "description":destDescription,
    "properties":[
        {"name": "remoteRepositoryURL",
        "value": remoteRepositoryURL},
        {"name": "localRepositoryLocation",
        "value": localRepositoryLocation},
        {"name": "userEmail",
        "value": userEmail},
        {"name": "credDomainID",
        "value": domain_name},
        {"name": "codeGenerationMode",
        "value": codeGenerationMode}]
}
```

instead of 

```
        {"name": "credDomainID",
        "value": domain_name},
```

should be

```
        {"name": "domainId",
        "value": domain_name},
```

Also, the Git Repository branch variable is not defined anywhere in the code.
Although, in SAS Environment Manager interface is well present.

Thank you.

**Comment by Criptic** [comment]
With the updated version of the notebook has been fixed. Can you confirm?

**Comment by kaponte75** [comment]
This issue has been resolved.
