### ISSUE TITLE
OSError: [Errno 6] No such device or address

### ISSUE THREAD

**Issue by Mespith** [sassoftware/open-model-manager-resources#3]
I'm trying to go through the [ImportPythonModel.ipynb](https://github.com/sassoftware/open-model-manager-resources/blob/master/examples/ImportPythonModel.ipynb) notebook in the examples. I do, however, get an error which I think needs to be solved in the package itself. 
![image](https://user-images.githubusercontent.com/7500718/77053373-8abc5800-69ce-11ea-9efd-ffc2c79eed1c.png)

I made a local copy of the package files and I changed line 150 in writeJSONFiles.py to
`modeler = getpass.getuser()`
Someone recommended getpass.getuser() to me since it checks the environment variables LOGNAME or USERNAME to find out who the user is, and falls back to pwd.getpwuid(os.getuid())[0] to get the login name of the current real user id. 

I tested it in my environment and it works like a charm. Maybe it would be an option in the pzmm package as well?

**Comment by smlindauer** [comment]
I tested the getpass.getuser() suggestion, but ran into another error on a different environment. 

Since this doesn't seem to be a one-size-fits-all situation, I am going to add a try/except block and a new argument into the function that allows for the user to specify the modeler name. It should look something like this:

```python
if modeler is None:
    try:
        modeler = getpass.getuser()
    except:
        modeler = 'defaultUser'
```
plus the additional `modeler=None` argument in the function call.

**Comment by kaponte75** [comment]
@Mespith the fixes from @smlindauer have been made to [ImportPythonModel.ipynb](https://github.com/sassoftware/open-model-manager-resources/blob/master/examples/ImportPythonModel.ipynb) example and the [writeJSONFiles.py](https://github.com/sassoftware/open-model-manager-resources/blob/master/addons/picklezip-mm/pzmm/writeJSONFiles.py)  Python script. If you have any additional issues, please let us know.

Thanks,
Kristen
