### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by zwyszomi** [sassoftware/open-model-manager-resources#30]
Hi
I'm using AZ Container Publishing Destination script on Viya 2021.2.5.
When executing admin_auth_token = mm_auth.get_auth_token(host_url, admin_userId, user_passwd) line
I'm getting SSLError: HTTPSConnectionPool(host='xyz.northeurope.cloudapp.azure.com', port=443): Max retries exceeded with url: /SASLogon/oauth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
How can I specify the certificate (I'm using Windows Python env)? I tried to import via mmc but getting the same error?

**Comment by kaponte75** [comment]
The related destination Jupyter notebook has been deprecated and replaced with a CLI example. The models plug-in to the SAS Viya CLI creates the base64 domain when creating the Azure publishing destination.
