### ISSUE TITLE
CalculateFitStatisticsROCLift.ipynb did not render dmcas_fitstat json file correctly

### ISSUE THREAD

**Issue by saspc** [sassoftware/open-model-manager-resources#5]
dmcas_fitstat.json doesn’t get formatted correctly when the first partition is (None,None). Fit statistics do not show in Open Model Manager. The following test rendered fit statistics successfully.

yTrainActual = df.yActual.to_list()
yTrainPredict = df.yPredict.to_list()
data = [(yTrainActual, yTrainPredict),
        (yTrainActual, yTrainPredict),
        (None, None)]

**Comment by smlindauer** [comment]
I have rewritten the logic for reading in different partitions of the dmcas_fitstat.json file to remove this error in formatting. Furthermore, I have removed an artifact that caused an empty partition set to still be viewed in the compare tab.

These changes have passed the testing phase and are now being reviewed before the final push to the repository.
