### ISSUE TITLE
pzmm: When importing models, the project destination is not always correct

### ISSUE THREAD

**Issue by smlindauer** [sassoftware/open-model-manager-resources#7]
Using the picklezip-mm package in the addons/ directory, if you attempt to import a model into a project that has a similar name with other projects in model manager, the destination is not always correct. 

For example, if two projects exist in model manager ('HMEQ' and 'QS_HMEQ'), and you attempt to import into the 'HMEQ' project, the model will end up in the 'QS_HMEQ' project.

**Comment by smlindauer** [comment]
The REST API filtering for MM does not use the f`?filter=eq(name, {projectName})` as documented. Instead of searching for an exact match, the filter is checking for any substring match.

In order to adjust for this, [uploadData.py](https://github.com/sassoftware/open-model-manager-resources/blob/master/addons/picklezip-mm/pzmm/uploadData.py) needs to be adjusted (specifically in the findProjectID() function on line 96). I will instead collect a list of all projects and search for an exact match in the resulting JSON file.

**Comment by jefurbee** [comment]
One of the two filter methods described [here](https://developer.sas.com/reference/filtering/) should work for the API. If not, I'd consider that a bug. A work-around may suffice for now, but causes more work for development.

**Comment by smlindauer** [comment]
It is a bug for Viya 3.5, but has been updated for 4.0. I figured a work-around that handles both cases would be best until everything is moved to 4.0.
