### ISSUE TITLE
Broken links in PZMM readme file

### ISSUE THREAD

**Issue by smlindauer** [sassoftware/open-model-manager-resources#9]
The samples and examples link in the [PZMM readme file](https://github.com/sassoftware/open-model-manager-resources/tree/master/addons/picklezip-mm) are broken locations. They should be pointed at https://github.com/sassoftware/open-model-manager-resources/tree/master/samples & https://github.com/sassoftware/open-model-manager-resources/tree/master/examples respectively.

**Comment by kaponte75** [comment]
When in a subdirectory using  "./ " does not work on GitHub for going up one level and linking to another directory.  You must use just a forward slash "/ ". Fixed links to directories and the license in the picklezip-mm/README.md.
